/* -----------------------------------------------------------------
 * Translated from examples/cvode/serial/cvDiurnal_kry_bp.c (CVODE 7.7.0)
 *
 * Example problem:
 *
 * An ODE system is generated from the following 2-species diurnal
 * kinetics advection-diffusion PDE system in 2 space dimensions:
 *
 * dc(i)/dt = Kh*(d/dx)^2 c(i) + V*dc(i)/dx + (d/dy)(Kv(y)*dc(i)/dy)
 *                 + Ri(c1,c2,t)      for i = 1,2,   where
 *   R1(c1,c2,t) = -q1*c1*c3 - q2*c1*c2 + 2*q3(t)*c3 + q4(t)*c2 ,
 *   R2(c1,c2,t) =  q1*c1*c3 - q2*c1*c2 - q4(t)*c2 ,
 *   Kv(y) = Kv0*exp(y/5) ,
 * Kh, V, Kv0, q1, q2, and c3 are constants, and q3(t) and q4(t)
 * vary diurnally. The problem is posed on the square
 *   0 <= x <= 20,    30 <= y <= 50   (all in km),
 * with homogeneous Neumann boundary conditions, and for time t in
 *   0 <= t <= 86400 sec (1 day).
 * The PDE system is treated by central differences on a uniform
 * 10 x 10 mesh, with simple polynomial initial profiles.
 * The problem is solved with CVODE, with the BDF/GMRES
 * method (i.e. using the SUNLinSol_SPGMR linear solver) and a banded
 * preconditioner, generated by difference quotients, using the
 * module CVBANDPRE. The problem is solved with left and right
 * preconditioning.
 * -----------------------------------------------------------------*/
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

use cvode_rs::sundials_utils::fmt_e;
use cvode_rs::*;

/* Problem Constants */

const ZERO: f64 = 0.0;
const ONE: f64 = 1.0;
const TWO: f64 = 2.0;

const NUM_SPECIES: i64 = 2; /* number of species         */
const KH: f64 = 4.0e-6; /* horizontal diffusivity Kh */
const VEL: f64 = 0.001; /* advection velocity V      */
const KV0: f64 = 1.0e-8; /* coefficient in Kv(y)      */
const Q1: f64 = 1.63e-16; /* coefficients q1, q2, c3   */
const Q2: f64 = 4.66e-16;
const C3: f64 = 3.7e16;
const A3: f64 = 22.62; /* coefficient in expression for q3(t) */
const A4: f64 = 7.601; /* coefficient in expression for q4(t) */
const C1_SCALE: f64 = 1.0e6; /* coefficients in initial profiles    */
const C2_SCALE: f64 = 1.0e12;

const T0: f64 = ZERO; /* initial time */
const NOUT: i32 = 12; /* number of output times */
const TWOHR: f64 = 7200.0; /* number of seconds in two hours  */
const HALFDAY: f64 = 4.32e4; /* number of seconds in a half day */
const PI: f64 = 3.1415926535898; /* pi */

const XMIN: f64 = ZERO; /* grid boundaries in x  */
const XMAX: f64 = 20.0;
const YMIN: f64 = 30.0; /* grid boundaries in y  */
const YMAX: f64 = 50.0;
const XMID: f64 = 10.0; /* grid midpoints in x,y */
const YMID: f64 = 40.0;

const MX: i64 = 10; /* MX = number of x mesh points */
const MY: i64 = 10; /* MY = number of y mesh points */
const NSMX: i64 = 20; /* NSMX = NUM_SPECIES*MX */
const MM: i64 = MX * MY; /* MM = MX*MY */

/* CVodeInit Constants */

const RTOL: f64 = 1.0e-5; /* scalar relative tolerance */
const FLOOR: f64 = 100.0; /* value of C1 or C2 at which tolerances */
/* change from relative to absolute      */
const ATOL: f64 = RTOL * FLOOR; /* scalar absolute tolerance */
const NEQ: i64 = NUM_SPECIES * MM; /* NEQ = number of equations */

/* User-defined vector and matrix accessor macro: IJKth */

/* IJKth is defined in order to isolate the translation from the
   mathematical 3-dimensional structure of the dependent variable vector
   to the underlying 1-dimensional storage.

   IJKth(vdata,i,j,k) references the element in the vdata array for
   species i at mesh point (j,k), where 1 <= i <= NUM_SPECIES,
   0 <= j <= MX-1, 0 <= k <= MY-1.
   For each mesh point (j,k), the elements for species i and i+1 are
   contiguous within vdata. */

macro_rules! IJKth {
    ($vdata:expr, $i:expr, $j:expr, $k:expr) => {
        $vdata[($i - 1 + ($j) * NUM_SPECIES + ($k) * NSMX) as usize]
    };
}

/* Type : UserDataStruct
   contains problem constants */

struct UserDataStruct {
    q4: f64,
    om: f64,
    dx: f64,
    dy: f64,
    hdco: f64,
    haco: f64,
    vdco: f64,
}

/*
 *-------------------------------
 * Private helper functions
 *-------------------------------
 */

/* Load problem constants in data */

fn InitUserData(data: &mut UserDataStruct) {
    data.om = PI / HALFDAY;
    data.dx = (XMAX - XMIN) / (MX - 1) as f64;
    data.dy = (YMAX - YMIN) / (MY - 1) as f64;
    data.hdco = KH / (data.dx * data.dx);
    data.haco = VEL / (TWO * data.dx);
    data.vdco = (ONE / (data.dy * data.dy)) * KV0;
}

/* Set initial conditions in u */

fn SetInitialProfiles(u: &mut NVector, dx: f64, dy: f64) {
    /* Set pointer to data array in vector u. */

    let udata = &mut u.data;

    /* Load initial profiles of c1 and c2 into u vector */

    for jy in 0..MY {
        let y = YMIN + jy as f64 * dy;
        let mut cy = (0.1 * (y - YMID)) * (0.1 * (y - YMID));
        cy = ONE - cy + 0.5 * (cy * cy);
        for jx in 0..MX {
            let x = XMIN + jx as f64 * dx;
            let mut cx = (0.1 * (x - XMID)) * (0.1 * (x - XMID));
            cx = ONE - cx + 0.5 * (cx * cx);
            IJKth!(udata, 1, jx, jy) = C1_SCALE * cx * cy;
            IJKth!(udata, 2, jx, jy) = C2_SCALE * cx * cy;
        }
    }
}

fn PrintIntro(mu: i64, ml: i64) {
    println!(
        "2-species diurnal advection-diffusion problem, {} by {} mesh",
        MX, MY
    );
    println!(
        "SPGMR solver; band preconditioner; mu = {}, ml = {}\n",
        mu, ml
    );
}

/* Print current t, step count, order, stepsize, and sampled c1,c2 values */

fn PrintOutput(cvode_mem: &mut CVodeMem, u: &NVector, t: f64) {
    let mut nst = 0i64;
    let mut qu = 0i32;
    let mut hu = ZERO;
    let mxh = MX / 2 - 1;
    let myh = MY / 2 - 1;
    let mx1 = MX - 1;
    let my1 = MY - 1;

    let udata = &u.data;

    let mut retval = CVodeGetNumSteps(cvode_mem, &mut nst);
    check_retval(retval, "CVodeGetNumSteps");
    retval = CVodeGetLastOrder(cvode_mem, &mut qu);
    check_retval(retval, "CVodeGetLastOrder");
    retval = CVodeGetLastStep(cvode_mem, &mut hu);
    check_retval(retval, "CVodeGetLastStep");

    println!(
        "t = {}   no. steps = {}   order = {}   stepsize = {}",
        fmt_e(t, 0, 2),
        nst,
        qu,
        fmt_e(hu, 0, 2)
    );
    println!(
        "c1 (bot.left/middle/top rt.) = {}  {}  {}",
        fmt_e(IJKth!(udata, 1, 0, 0), 12, 3),
        fmt_e(IJKth!(udata, 1, mxh, myh), 12, 3),
        fmt_e(IJKth!(udata, 1, mx1, my1), 12, 3)
    );
    println!(
        "c2 (bot.left/middle/top rt.) = {}  {}  {}\n",
        fmt_e(IJKth!(udata, 2, 0, 0), 12, 3),
        fmt_e(IJKth!(udata, 2, mxh, myh), 12, 3),
        fmt_e(IJKth!(udata, 2, mx1, my1), 12, 3)
    );
}

/* Get and print final statistics */

fn PrintFinalStats(cvode_mem: &mut CVodeMem) {
    let (mut lenrw, mut leniw) = (0i64, 0i64);
    let (mut lenrwLS, mut leniwLS) = (0i64, 0i64);
    let (mut lenrwBP, mut leniwBP) = (0i64, 0i64);
    let (mut nst, mut nfe, mut nsetups, mut nni, mut ncfn, mut netf) =
        (0i64, 0i64, 0i64, 0i64, 0i64, 0i64);
    let (mut nli, mut npe, mut nps, mut ncfl, mut nfeLS) = (0i64, 0i64, 0i64, 0i64, 0i64);
    let mut nfeBP = 0i64;

    let mut retval = CVodeGetWorkSpace(cvode_mem, &mut lenrw, &mut leniw);
    check_retval(retval, "CVodeGetWorkSpace");
    retval = CVodeGetNumSteps(cvode_mem, &mut nst);
    check_retval(retval, "CVodeGetNumSteps");
    retval = CVodeGetNumRhsEvals(cvode_mem, &mut nfe);
    check_retval(retval, "CVodeGetNumRhsEvals");
    retval = CVodeGetNumLinSolvSetups(cvode_mem, &mut nsetups);
    check_retval(retval, "CVodeGetNumLinSolvSetups");
    retval = CVodeGetNumErrTestFails(cvode_mem, &mut netf);
    check_retval(retval, "CVodeGetNumErrTestFails");
    retval = CVodeGetNumNonlinSolvIters(cvode_mem, &mut nni);
    check_retval(retval, "CVodeGetNumNonlinSolvIters");
    retval = CVodeGetNumNonlinSolvConvFails(cvode_mem, &mut ncfn);
    check_retval(retval, "CVodeGetNumNonlinSolvConvFails");

    retval = CVodeGetLinWorkSpace(cvode_mem, &mut lenrwLS, &mut leniwLS);
    check_retval(retval, "CVodeGetLinWorkSpace");
    retval = CVodeGetNumLinIters(cvode_mem, &mut nli);
    check_retval(retval, "CVodeGetNumLinIters");
    retval = CVodeGetNumPrecEvals(cvode_mem, &mut npe);
    check_retval(retval, "CVodeGetNumPrecEvals");
    retval = CVodeGetNumPrecSolves(cvode_mem, &mut nps);
    check_retval(retval, "CVodeGetNumPrecSolves");
    retval = CVodeGetNumLinConvFails(cvode_mem, &mut ncfl);
    check_retval(retval, "CVodeGetNumLinConvFails");
    retval = CVodeGetNumLinRhsEvals(cvode_mem, &mut nfeLS);
    check_retval(retval, "CVodeGetNumLinRhsEvals");

    retval = CVBandPrecGetWorkSpace(cvode_mem, &mut lenrwBP, &mut leniwBP);
    check_retval(retval, "CVBandPrecGetWorkSpace");
    retval = CVBandPrecGetNumRhsEvals(cvode_mem, &mut nfeBP);
    check_retval(retval, "CVBandPrecGetNumRhsEvals");

    println!("\nFinal Statistics.. \n");
    println!("lenrw   = {:5}     leniw   = {:5}", lenrw, leniw);
    println!("lenrwls = {:5}     leniwls = {:5}", lenrwLS, leniwLS);
    println!("lenrwbp = {:5}     leniwbp = {:5}", lenrwBP, leniwBP);
    println!("nst     = {:5}", nst);
    println!("nfe     = {:5}     nfetot  = {:5}", nfe, nfe + nfeLS + nfeBP);
    println!("nfeLS   = {:5}     nfeBP   = {:5}", nfeLS, nfeBP);
    println!("nni     = {:5}     nli     = {:5}", nni, nli);
    println!("nsetups = {:5}     netf    = {:5}", nsetups, netf);
    println!("npe     = {:5}     nps     = {:5}", npe, nps);
    println!("ncfn    = {:5}     ncfl    = {:5}\n", ncfn, ncfl);
}

/* Check function return value */
fn check_retval(retval: i32, funcname: &str) -> bool {
    if retval < 0 {
        eprintln!(
            "\nSUNDIALS_ERROR: {}() failed with retval = {}\n",
            funcname, retval
        );
        return true;
    }
    false
}

/* SUNLinSol_SPGMRSetPrecType: in C the example keeps the SUNLinearSolver
   handle LS after attaching it to CVode; here ownership of the solver
   moved into cvode_mem, so reach the SPGMR solver through the CVLS
   memory to change its preconditioning type. */

fn SUNLinSol_SPGMRSetPrecType(cvode_mem: &mut CVodeMem, pretype: i32) -> i32 {
    if let LsModule::Ls(cvls_mem) = &mut cvode_mem.cv_lmem {
        if let LinearSolver::Spgmr(spgmr) = &mut cvls_mem.LS {
            return spgmr.set_prec_type(pretype);
        }
    }
    -1
}

/*
 *-------------------------------
 * Function called by the solver
 *-------------------------------
 */

/* f routine. Compute RHS function f(t,u). */

fn f(t: f64, u: &NVector, udot: &mut NVector, user_data: &mut UserData) -> i32 {
    let data = user_data
        .as_mut()
        .unwrap()
        .downcast_mut::<UserDataStruct>()
        .unwrap();
    let udata = &u.data;
    let dudata = &mut udot.data;

    /* Set diurnal rate coefficients. */

    let s = (data.om * t).sin();
    let q3: f64;
    if s > ZERO {
        q3 = (-A3 / s).exp();
        data.q4 = (-A4 / s).exp();
    } else {
        q3 = ZERO;
        data.q4 = ZERO;
    }

    /* Make local copies of problem variables, for efficiency. */

    let q4coef = data.q4;
    let dely = data.dy;
    let verdco = data.vdco;
    let hordco = data.hdco;
    let horaco = data.haco;

    /* Loop over all grid points. */

    for jy in 0..MY {
        /* Set vertical diffusion coefficients at jy +- 1/2 */

        let ydn = YMIN + (jy as f64 - 0.5) * dely;
        let yup = ydn + dely;
        let cydn = verdco * (0.2 * ydn).exp();
        let cyup = verdco * (0.2 * yup).exp();
        let idn: i64 = if jy == 0 { 1 } else { -1 };
        let iup: i64 = if jy == MY - 1 { -1 } else { 1 };
        for jx in 0..MX {
            /* Extract c1 and c2, and set kinetic rate terms. */

            let c1 = IJKth!(udata, 1, jx, jy);
            let c2 = IJKth!(udata, 2, jx, jy);
            let qq1 = Q1 * c1 * C3;
            let qq2 = Q2 * c1 * c2;
            let qq3 = q3 * C3;
            let qq4 = q4coef * c2;
            let rkin1 = -qq1 - qq2 + TWO * qq3 + qq4;
            let rkin2 = qq1 - qq2 - qq4;

            /* Set vertical diffusion terms. */

            let c1dn = IJKth!(udata, 1, jx, jy + idn);
            let c2dn = IJKth!(udata, 2, jx, jy + idn);
            let c1up = IJKth!(udata, 1, jx, jy + iup);
            let c2up = IJKth!(udata, 2, jx, jy + iup);
            let vertd1 = cyup * (c1up - c1) - cydn * (c1 - c1dn);
            let vertd2 = cyup * (c2up - c2) - cydn * (c2 - c2dn);

            /* Set horizontal diffusion and advection terms. */

            let ileft: i64 = if jx == 0 { 1 } else { -1 };
            let iright: i64 = if jx == MX - 1 { -1 } else { 1 };
            let c1lt = IJKth!(udata, 1, jx + ileft, jy);
            let c2lt = IJKth!(udata, 2, jx + ileft, jy);
            let c1rt = IJKth!(udata, 1, jx + iright, jy);
            let c2rt = IJKth!(udata, 2, jx + iright, jy);
            let hord1 = hordco * (c1rt - TWO * c1 + c1lt);
            let hord2 = hordco * (c2rt - TWO * c2 + c2lt);
            let horad1 = horaco * (c1rt - c1lt);
            let horad2 = horaco * (c2rt - c2lt);

            /* Load all terms into udot. */

            IJKth!(dudata, 1, jx, jy) = vertd1 + hord1 + horad1 + rkin1;
            IJKth!(dudata, 2, jx, jy) = vertd2 + hord2 + horad2 + rkin2;
        }
    }

    0
}

/*
 *-------------------------------
 * Main Program
 *-------------------------------
 */

fn main() {
    /* Create the SUNDIALS context */
    let sunctx = SUNContext_Create();

    /* Allocate and initialize u, and set problem data and tolerances */
    let mut u = N_VNew_Serial(NEQ, &sunctx);
    let mut data = UserDataStruct {
        q4: ZERO,
        om: ZERO,
        dx: ZERO,
        dy: ZERO,
        hdco: ZERO,
        haco: ZERO,
        vdco: ZERO,
    };
    InitUserData(&mut data);
    SetInitialProfiles(&mut u, data.dx, data.dy);
    let abstol = ATOL;
    let reltol = RTOL;

    /* Call CVodeCreate to create the solver memory and specify the
     * Backward Differentiation Formula */
    let mut cvode_mem = CVodeCreate(CV_BDF, &sunctx);

    /* Set the pointer to user-defined data */
    let mut retval = CVodeSetUserData(&mut cvode_mem, Some(Box::new(data)));
    if check_retval(retval, "CVodeSetUserData") {
        std::process::exit(1);
    }

    /* Call CVodeInit to initialize the integrator memory and specify the
     * user's right hand side function in u'=f(t,u), the initial time T0, and
     * the initial dependent variable vector u. */
    retval = CVodeInit(&mut cvode_mem, f, T0, &u);
    if check_retval(retval, "CVodeInit") {
        std::process::exit(1);
    }

    /* Call CVodeSStolerances to specify the scalar relative tolerance
     * and scalar absolute tolerances */
    retval = CVodeSStolerances(&mut cvode_mem, reltol, abstol);
    if check_retval(retval, "CVodeSStolerances") {
        std::process::exit(1);
    }

    /* Call SUNLinSol_SPGMR to specify the linear solver SPGMR
     * with left preconditioning and the default Krylov dimension */
    let ls = SUNLinSol_SPGMR(&u, SUN_PREC_LEFT, 0, &sunctx);

    /* Call CVodeSetLinearSolver to attach the linear solver to CVode */
    retval = CVodeSetLinearSolver(&mut cvode_mem, ls, None);
    if check_retval(retval, "CVodeSetLinearSolver") {
        std::process::exit(1);
    }

    /* Call CVBandPreInit to initialize band preconditioner */
    let ml: i64 = 2;
    let mu: i64 = 2;
    retval = CVBandPrecInit(&mut cvode_mem, NEQ, mu, ml);
    if check_retval(retval, "CVBandPrecInit") {
        std::process::exit(1);
    }

    PrintIntro(mu, ml);

    /* Loop over jpre (= SUN_PREC_LEFT, SUN_PREC_RIGHT), and solve the problem */

    let mut t = ZERO;
    for jpre in SUN_PREC_LEFT..=SUN_PREC_RIGHT {
        /* On second run, re-initialize u, the solver, and SPGMR */

        if jpre == SUN_PREC_RIGHT {
            let (dx, dy) = {
                let data = cvode_mem
                    .cv_user_data
                    .as_ref()
                    .unwrap()
                    .downcast_ref::<UserDataStruct>()
                    .unwrap();
                (data.dx, data.dy)
            };
            SetInitialProfiles(&mut u, dx, dy);

            retval = CVodeReInit(&mut cvode_mem, T0, &u);
            if check_retval(retval, "CVodeReInit") {
                std::process::exit(1);
            }

            retval = SUNLinSol_SPGMRSetPrecType(&mut cvode_mem, SUN_PREC_RIGHT);
            if check_retval(retval, "SUNLinSol_SPGMRSetPrecType") {
                std::process::exit(1);
            }

            retval = CVBandPrecInit(&mut cvode_mem, NEQ, mu, ml);
            if check_retval(retval, "CVBandPrecInit") {
                std::process::exit(1);
            }

            print!("\n\n-------------------------------------------------------");
            println!("------------");
        }

        println!(
            "\n\nPreconditioner type is:  jpre = {}\n",
            if jpre == SUN_PREC_LEFT {
                "SUN_PREC_LEFT"
            } else {
                "SUN_PREC_RIGHT"
            }
        );

        /* In loop over output points, call CVode, print results, test for error */

        let mut tout = TWOHR;
        for _iout in 1..=NOUT {
            retval = CVode(&mut cvode_mem, tout, &mut u, &mut t, CV_NORMAL);
            check_retval(retval, "CVode");
            PrintOutput(&mut cvode_mem, &u, t);
            if retval != CV_SUCCESS {
                break;
            }
            tout += TWOHR;
        }

        /* Print final statistics */

        PrintFinalStats(&mut cvode_mem);
    } /* End of jpre loop */

    /* Free memory */
    CVodeFree(cvode_mem);
}
