[package]
name = "idas_rs"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Pure-Rust, memory-safe translation of idas v7.7.0 (SUNDIALS)"

[dependencies]
sundials_core = { path = "../sundials_core" }

[[example]]
name = "idasRoberts_dns"

[[example]]
name = "idasHeat2D_bnd"

[[example]]
name = "idasHeat2D_kry"

[[example]]
name = "idasFoodWeb_bnd"

[[example]]
name = "idasKrylovDemo_ls"

[[example]]
name = "idasAnalytic_mels"

[[example]]
name = "idasSlCrank_dns"

[[example]]
name = "idasAkzoNob_dns"

[[example]]
name = "idasRoberts_FSA_dns"

[[example]]
name = "idasSlCrank_FSA_dns"

[[example]]
name = "idasRoberts_ASAi_dns"

[[example]]
name = "idasAkzoNob_ASAi_dns"
